// <auto-generated />
using DWHouse_Dashboard.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dashboard_DW_V2.Migrations.ApplicationDB
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Dashboard_DW_V2.Models.EmailDataChartBar", b =>
                {
                    b.Property<int>("Month")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Month"), 1L, 1);

                    b.Property<int>("CountEmailsOpened")
                        .HasColumnType("int");

                    b.Property<int>("CountSent")
                        .HasColumnType("int");

                    b.Property<int>("CountSentSuccesful")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Month");

                    b.ToTable("EmailChartBar");
                });

            modelBuilder.Entity("Dashboard_DW_V2.Models.PreferencesDataToPieChart", b =>
                {
                    b.Property<int>("Count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Count"), 1L, 1);

                    b.Property<int>("CountEmailOptin")
                        .HasColumnType("int");

                    b.Property<int>("CountMailOptin")
                        .HasColumnType("int");

                    b.Property<int>("CountMoreThanOneOptin")
                        .HasColumnType("int");

                    b.Property<int>("CountNoOptin")
                        .HasColumnType("int");

                    b.Property<int>("CountPhoneOptin")
                        .HasColumnType("int");

                    b.Property<int>("CountSmsOptin")
                        .HasColumnType("int");

                    b.HasKey("Count");

                    b.ToTable("PreferencestoChartPie");
                });

            modelBuilder.Entity("Dashboard_DW_V2.Models.VisitChart", b =>
                {
                    b.Property<string>("MonthYear")
                        .HasColumnType("nvarchar(450)");

                    b.Property<float>("DirectSpent")
                        .HasColumnType("real");

                    b.Property<float>("IndirectSpent")
                        .HasColumnType("real");

                    b.Property<int>("Visitors")
                        .HasColumnType("int");

                    b.HasKey("MonthYear");

                    b.ToTable("visitChart");
                });
#pragma warning restore 612, 618
        }
    }
}
